# Generated by Django 4.2.7 on 2023-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
