# Generated by Django 4.2.5 on 2023-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
