# Generated by Django 4.2.7 on 2023-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_check',
            field=models.CharField(choices=[('T', 'Còn hạn'), ('F', 'Hết hạn')], default='T', max_length=20),
        ),
    ]
