# Generated by Django 4.2.5 on 2023-11-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
    ]
