# Generated by Django 4.2.7 on 2023-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking_book_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_check',
            field=models.CharField(choices=[('Còn hạn', 'Còn hạn'), ('Hết hạn', 'Hết hạn')], max_length=20),
        ),
    ]
