# Generated by Django 4.2.7 on 2023-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_max',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_min',
            field=models.IntegerField(default=1),
        ),
    ]
