# Generated by Django 4.2.5 on 2023-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_room_created_by_remove_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
