# Generated by Django 4.2.7 on 2023-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_booking_book_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default=5, max_length=10),
        ),
    ]
