# Generated by Django 4.2.7 on 2023-11-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_comment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Nhận_xét',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rate',
            new_name='Đánh_giá',
        ),
    ]
