# Generated by Django 4.2.5 on 2023-11-10 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='book_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='room',
            name='book_out',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
