# Generated by Django 4.2.7 on 2023-11-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_room_created_by_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
